require mp_path('mp/sinatra/helpers/auth')
require mp_path('mp/sinatra/helpers/debug')
require mp_path('mp/sinatra/helpers/templates')
require mp_path('mp/sinatra/helpers/app_context')
require mp_path('mp/sinatra/helpers/ajax')
require mp_path('mp/sinatra/helpers/gravatar')
require mp_path('mp/sinatra/helpers/pagination')
