source 'http://rubygems.org'

gem 'bundler'
gem 'rack', '~> 1.3.6'
gem 'sinatra', '~> 1.3.2'
gem 'rake', '~> 0.9.2'

gem 'warden', '~> 1.1'
gem 'bcrypt-ruby', '~> 3.0'

gem 'bureaucrat', git: 'git://github.com/gonz/bureaucrat.git', ref: '82e38e'
gem 'queue_classic', '2.0.0rc4'

group :dev do
  gem 'sass'
  gem 'compass'
  gem 'racksh', '~> 0.9.11'
  gem 'shotgun'
  gem 'unicorn'
  gem 'hooves' # unicorns can ride shotgun, too
  gem 'pry'
  gem 'ruby-debug19'
end

# These are deps needed for consumer app models.
group :consumer_models do
  # Activerecord
  gem 'pg', '~> 0.13.2'
  gem 'activerecord', '~> 3.1.2'
  gem 'bitmask_attributes', :git => 'git://github.com/sborrazas/bitmask_attributes.git'
  # Actionpack
  gem 'actionpack', '~> 3.1.4' # required lib/file_size_validator.rb
  # Geocoder
  gem 'geocoder', '~> 1.1.1'
  # Carrierwave
  gem 'carrierwave', '~> 0.5.8'
  gem 'mini_magick', '~> 3.4'
  gem 'fog', '~> 0.9.0'
  # Recurly
  gem 'recurly', '~> 2.0.11'
end

