defaults: &defaults
  host: localhost
  port: 6379
  password: lucam0nthly

development:
  host: localhost
  port: 6379

demo:
  <<: *defaults
staging:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
