class StringsDefaultToEmpty < ActiveRecord::Migration
  def up
    change_column(:adjustments, :recurly_code, :string, null: false, default: '', limit: 50)
    change_column(:admin_activities, :verb, :string, null: false, default: '')
    change_column(:admin_activities, :object_type, :string, null: false, default: '')
    change_column(:attachments, :image, :string, null: false, default: '')
    change_column(:attachments, :attachable_type, :string, null: false, default: '')
    change_column(:authentications, :provider, :string, null: false, default: '')
    change_column(:authentications, :uid, :string, null: false, default: '')
    change_column(:billing_infos, :address1, :string, null: false, default: '')
    change_column(:billing_infos, :address2, :string, null: false, default: '')
    change_column(:billing_infos, :city, :string, null: false, default: '')
    change_column(:billing_infos, :state, :string, null: false, default: '')
    change_column(:billing_infos, :zip, :string, null: false, default: '')
    change_column(:billing_infos, :month, :string, null: false, default: '')
    change_column(:billing_infos, :year, :string, null: false, default: '')
    change_column(:billing_infos, :ip_address, :string, null: false, default: '')
    change_column(:categories, :name, :string, null: false, default: '')
    change_column(:categories, :image, :string, null: false, default: '')
    change_column(:categories, :thumbnail, :string, null: false, default: '')
    change_column(:categories, :icon, :string, null: false, default: '')
    change_column(:category_groups, :name, :string, null: false, default: '')
    change_column(:category_groups, :image, :string, null: false, default: '')
    change_column(:category_groups, :icon, :string, null: false, default: '')
    change_column(:cities, :name, :string, null: false, default: '')
    change_column(:cities, :state_code, :string, null: false, default: '')
    change_column(:cities, :image, :string, null: false, default: '')
    change_column(:cities, :google_name, :string, null: false, default: '')
    change_column(:coupons, :coupon_code, :string, null: false, default: '')
    change_column(:coupons, :name, :string, null: false, default: '')
    change_column(:coupons, :marketing_description, :string, null: false, default: '')
    change_column(:coupons, :invoice_description, :string, null: false, default: '')
    change_column(:coupons, :discount_type, :string, null: false, default: '')
    change_column(:coupons, :image, :string, null: false, default: '')
    change_column(:coupons, :recurly_code, :string, null: false, default: '')
    change_column(:documents, :name, :string, null: false, default: '')
    change_column(:documents, :file, :string, null: false, default: '')
    change_column(:email_recipients, :email, :string, null: false, default: '')
    change_column(:email_recipients, :emailable_type, :string, null: false, default: '')
    change_column(:email_recipients, :exact_target_id, :string, null: false, default: '')
    change_column(:faqs, :question, :string, null: false, default: '')
    change_column(:friends, :email, :string, null: false, default: '')
    change_column(:invoice_lines, :uuid, :string, null: false, default: '', limit: 32)
    change_column(:invoice_lines, :description, :string, null: false, default: '')
    change_column(:invoice_lines, :origin, :string, null: false, default: '')
    change_column(:invoices, :uuid, :string, null: false, default: '')
    change_column(:invoices, :status, :string, null: false, default: '')
    change_column(:marketing_deal_sources, :url_code, :string, null: false, default: '')
    change_column(:marketing_deal_sources, :name, :string, null: false, default: '')
    change_column(:marketing_deal_sources, :image, :string, null: false, default: '')
    change_column(:marketing_user_attachments, :image, :string, null: false, default: '')
    change_column(:marketing_user_attachments, :attachment_type, :string, null: false, default: '')
    change_column(:marketing_video_reviews, :raw_url, :string, null: false, default: '')
    change_column(:marketing_video_reviews, :title, :string, null: false, default: '')
    change_column(:marketing_video_reviews, :author, :string, null: false, default: '')
    change_column(:merchants, :business_name, :string, null: false, default: '')
    change_column(:merchants, :location, :string, null: false, default: '')
    change_column(:merchants, :image, :string, null: false, default: '')
    change_column(:merchants, :logo, :string, null: false, default: '')
    change_column(:merchants, :video_url, :string, null: false, default: '')
    change_column(:merchants, :video_thumbnail_url, :string, null: false, default: '')
    change_column(:merchants, :email, :string, null: false, default: '')
    change_column(:merchants, :address1, :string, null: false, default: '')
    change_column(:merchants, :address2, :string, null: false, default: '')
    change_column(:merchants, :zipcode, :string, null: false, default: '')
    change_column(:merchants, :city, :string, null: false, default: '')
    change_column(:merchants, :country, :string, null: false, default: '')
    change_column(:merchants, :state, :string, null: false, default: '')
    change_column(:merchants, :phone, :string, null: false, default: '')
    change_column(:merchants, :contact_name, :string, null: false, default: '')
    change_column(:merchants, :contact_last_name, :string, null: false, default: '')
    change_column(:merchants, :website, :string, null: false, default: '')
    change_column(:merchants, :business_type, :string, null: false, default: '')
    change_column(:merchants, :business_size, :string, null: false, default: '')
    change_column(:merchants, :management_config, :string, null: false, default: '')
    change_column(:merchants, :assistance_config, :string, null: false, default: '')
    change_column(:merchants, :shipping_type, :string, null: false, default: '', limit: 20)
    change_column(:merchants, :marketing_phrase, :string, null: false, default: '')
    change_column(:merchants, :taxation_policy, :string, null: false, default: 'no_taxes')
    change_column(:merchants, :custom_site_url, :string, null: false, default: '')
    change_column(:merchants, :tagline, :string, null: false, default: '')
    change_column(:merchants, :facebook_url, :string, null: false, default: '')
    change_column(:merchants, :twitter_url, :string, null: false, default: '')
    change_column(:merchants, :custom_site_base_color, :string, null: false, default: '', limit: 6)
    change_column(:merchants, :about_image, :string, null: false, default: '')
    change_column(:merchants, :storefront_logo, :string, null: false, default: '')
    change_column(:merchants, :storefront_heading, :string, null: false, default: '')
    change_column(:merchants, :custom_message_type, :string, null: false, default: '')
    change_column(:option_groups, :description, :string, null: false, default: '')
    change_column(:option_groups, :option_type, :string, null: false, default: '', limit: 20)
    change_column(:option_recurly_codes, :recurly_code, :string, null: false, default: '')
    change_column(:option_recurly_codes, :status, :string, null: false, default: '', limit: 20)
    change_column(:options, :title, :string, null: false, default: '')
    change_column(:options, :image, :string, null: false, default: '')
    change_column(:options, :invoice_description, :string, null: false, default: '')
    change_column(:plan_documents, :name, :string, null: false, default: '')
    change_column(:plan_documents, :description, :string, null: false, default: '')
    change_column(:plan_documents, :file, :string, null: false, default: '')
    change_column(:plan_recurrences, :status, :string, null: false, default: '', limit: 20)
    change_column(:plan_recurrences, :recurrence_type, :string, null: false, default: '', limit: 40)
    change_column(:plan_recurrences, :recurly_plan_code, :string, null: false, default: '', limit: 50)
    change_column(:plans, :name, :string, null: false, default: '')
    change_column(:plans, :marketing_phrase, :string, null: false, default: '')
    change_column(:plans, :thumbnail, :string, null: false, default: '')
    change_column(:plans, :icon, :string, null: false, default: '')
    change_column(:plans, :status, :string, null: false, default: 'pending')
    change_column(:plans, :unique_hash, :string, null: false, default: '')
    change_column(:plans, :plan_type, :string, null: false, default: '', limit: 40)
    change_column(:plans, :short_description, :string, null: false, default: '')
    change_column(:plans, :notes_to_customer, :string, null: false, default: '')
    change_column(:plans, :merchant_storefront_image, :string, null: false, default: '')
    change_column(:registry, :key, :string, null: false, default: '')
    change_column(:registry, :value, :string, null: false, default: '')
    change_column(:shipments, :tracking_number, :string, null: false, default: '')
    change_column(:shipping_infos, :first_name, :string, null: false, default: '')
    change_column(:shipping_infos, :last_name, :string, null: false, default: '')
    change_column(:shipping_infos, :address1, :string, null: false, default: '')
    change_column(:shipping_infos, :address2, :string, null: false, default: '')
    change_column(:shipping_infos, :zipcode_str, :string, null: false, default: '')
    change_column(:shipping_infos, :phone, :string, null: false, default: '')
    change_column(:shipping_infos, :delivery_instructions, :string, null: false, default: '')
    change_column(:shipping_infos, :city, :string, null: false, default: '')
    change_column(:states, :code, :string, null: false, default: '')
    change_column(:states, :name, :string, null: false, default: '')
    change_column(:subscriptions, :recurly_code, :string, null: false, default: '')
    change_column(:subscriptions, :shipping_type, :string, null: false, default: '')
    change_column(:subscriptions, :recurly_coupon_code, :string, null: false, default: '')
    change_column(:superhub_plans, :title, :string, null: false, default: '')
    change_column(:superhub_plans, :subtitle, :string, null: false, default: '')
    change_column(:tag_highlights, :image, :string, null: false, default: '')
    change_column(:tag_highlights, :title, :string, null: false, default: '')
    change_column(:tag_highlights, :highlight_type, :string, null: false, default: '')
    change_column(:tag_highlights, :price_recurrence, :string, null: false, default: '')
    change_column(:tags, :keyword, :string, null: false, default: '')
    change_column(:user_preferences, :status, :string, null: false, default: '')
    change_column(:zipcodes, :number, :string, null: false, default: '')
  end

  def down
  end
end
